"""Revision

Revision ID: f4d9094520ed
Revises: cd2419f8d48c
Create Date: 2022-07-10 13:32:01.339022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d9094520ed'
down_revision = 'cd2419f8d48c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
